import { cn } from '@/lib/utils'
import '../styles/globals.css'

import { BackgroundImage } from '@/components/background-image'
import { inter } from '@/styles/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Daniel Rodrigues | Dev Links',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body
        className={cn(
          'bg-background text-foreground dark relative flex min-h-screen items-center justify-center font-sans',
          inter.variable,
        )}
      >
        <BackgroundImage />

        {children}
      </body>
    </html>
  )
}
