import '../styles/globals.css'

import { inter } from '@/styles/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Daniel Rodrigues | Dev Links',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} bg-background text-foreground dark relative flex min-h-screen items-center justify-center font-sans`}
      >
        <div className="bg-home absolute inset-0 -z-10 bg-cover bg-center bg-no-repeat" />
        {children}
      </body>
    </html>
  )
}
